import React from 'react';
import SideMenu from '../components/side-menu';

const Before = () => {
    return (
        <div className='page-wrapper'>
            <SideMenu active='before'/>
            <div className='content'>
                
                <img className='banner' alt='' src='/assets/images/before/Before_Banner.png'/>
                <h2 className='content-title pink'>BEFORE THE PALACE</h2>
                <h3 className='content-subtitle'>POLICING AND TORONTO'S QUEER COMMUNITIES (1974-1999)</h3>
                
                <p>
                    The Pussy Palace, first launched in 1998, marked a radical and celebratory moment in Toronto’s queer and trans history. Organized by and for queer women and trans people, these bathhouse events created a daring space for public sexual expression and community-building in ways rarely seen before—and, arguably, never since. The brilliance of the Pussy Palace lies in its unapologetic celebration of sexual freedom and queer pleasure, standing in contrast to decades of police repression and efforts to criminalize non-normative sexuality in the city. 
                </p>
                <p>
                    Despite its novelty, the Pussy Palace did not emerge in isolation. Rather, the history of police harassment from the 1970s to the 1990s shaped the conditions under which the Pussy Palace was created and ultimately raided. From the defiance of the Brunswick Four in 1974 to the notorious bathhouse raids targeting gay men in the late 1970s and early 1980s, queer and trans communities, alongside sex workers and their allies, had long resisted police surveillance and control. This persecution did not end with so-called decriminalization efforts but instead shifted to more insidious forms of targeting public spaces, including bathhouses and areas where sex work took place. Throughout the 1980s and 1990s, this state-sanctioned violence disproportionately affected marginalized groups, with queer and sex-working communities at the forefront. The creation of the Pussy Palace was a direct challenge to this legacy of harassment, offering a bold reclamation of space and pleasure, rooted in radical sex activism. 
                </p>
                
                <h2 className="pink content-page-subheader">THE BRUNSWICK FOUR: DYKES FIGHT BACK (1974) </h2>
                <img className='banner' src='/assets/images/before/Brunswick Four.jpg'></img>
                <p className='text-page-inline-caption'>Photograph of The Brunswick Four (1974), courtesy of The ArQuives: Canada‘s LGBTQ2+ Archives. From left: Adrienne Rosen (formerly Adrienne Potts), Pat Murphy, Sue Wells, and Lamar Van Dyke (formerly Heather Elizabeth Nelson). Copyright Aaron Devor. </p>
            
                <p>Toronto police have a long history of harassing lesbians and queer women, but it wasn’t until the 1970s that queer women began to loudly and visibly fight back. One pivotal moment was the Brunswick Four incident on January 5, 1974, which set an important precedent for the Toronto Women’s Bathhouse Committee’s activism after the Pussy Palace police raid. </p>
                <p>That night, at the Brunswick House, a popular pub hosting an amateur open mic, four lesbians — <a href="https://digitalexhibitions.arquives.ca/items/show/139">Pat Murphy</a>, Adrienne Rosen (formerly, Potts), <a href="https://www.youtube.com/watch?v=Sinp1MDQbI0">Sue Wells</a>, and <a href="https://www.newyorker.com/magazine/2009/03/02/lesbian-nation">Lamar Van Dyke</a> (formerly, Heather Elizabeth Nelson) — responded to harassment from other patrons by singing “I Enjoy Being a Dyke,” a parody of the Rodgers and Hammerstein classic “I Enjoy Being a Girl.” The pub manager accused them of trying to start a “lesbian riot,” and eight police officers arrived to remove them. Since they weren’t charged with any crime, the women refused to leave, but police threw them into a paddy wagon anyway. At the station, they were denied the right to a lawyer and, after some time, were literally thrown out (Rosen got punched in the process). </p>
                <p>The women returned to the pub to gather witness statements, only for three of them to be taken back to the station, where they were harassed and charged with creating a disturbance. The queer community quickly rallied, organizing fundraising dances and a defence fund. At trial, Rosen was convicted, while Van Dyke and Murphy were acquitted. The Brunswick Four incident marked a turning point: the arrest and trial received major media coverage — a first for queer women and police harassment — proving that, with the community behind them, dykes fight back!</p>
            
                <h2 className="pink content-page-subheader">GAY MALE BATHHOUSE RAIDS (1978-81)</h2>
                <img className='banner' src='/assets/images/before/Operation Soap.jpg'></img>
                <p className='text-page-inline-caption'>“Operation Soap” in progress outside Club Toronto, 231 Mutual Street, future site of the Pussy Palace bathhouse events. Photograph by Frank Lennon (Feb 8, 1981). Copyright Toronto Star.</p>

                <p>Although the 1969 amendments to the Canadian Criminal Code decriminalized queer sex between two people, public spaces remained criminalized under “common bawdy house” provisions, which defined a bawdy house as any location used for prostitution or acts of indecency. Bathhouses became key targets for police, as these spaces were central to gay men’s sexual culture. </p>
                <p>On December 9, 1978, 20 cops raided The Barracks, a downtown Toronto bathhouse. Police smashed into rooms, broke open lockers, kicked holes in the walls, and confiscated a membership list of 800. They charged 23 men for being “found-ins” and five for being “keepers” of a common bawdy house. In response, gay activists founded what became known as the Right to Privacy Committee (RTPC), which raised funds for legal fees, represented gay men in court, and demanded police accountability. Six months later, in August 1979, white police officers executed an unarmed Black man, Albert Johnson, in his home. The Right to Privacy Committee joined Black, South Asian, and other minority groups to protest racism and police brutality in a period of coalitional activism against racism and homophobia. On February 5, 1981, Toronto police launched “Operation Soap,” with 150 police officers arresting nearly 300 gay men in an orchestrated raid of four bathhouses, including Club Toronto — future site of the Pussy Palace bathhouse events. Although these were not the first bathhouse raids nor the last (in fact, the police raided two more bathhouses on June 16), the 1981 raids are distinctive for their size, the degree of police violence, the increase in street violence against LGBTQ people in the aftermath, and the intensity of LGBTQ activism in response. </p>
                <p><i>Xtra</i> magazine provides a brief yet insightful overview of the raids in <a href="https://www.youtube.com/watch?v=3a9b0P2x_uQ">this short video</a>, which features interview footage by filmmaker Nancy Nicol. For a deeper dive into Nicol’s work, <a href="https://digitalexhibitions.arquives.ca/exhibits/show/nancy-nicol/-operation-soap">explore her collection</a> at The ArQuives. </p>
            
                <h2 className='pink content-page-subheader'>QUEERNESS, SEX WORK, AND THE POLICE (1981-1999) </h2>
                
                <p>The policing of queerness and sex work in Toronto has a deeply intertwined history, rooted in the same legal mechanisms used to target bathhouses in the 1970s and 1980s. Just as gay men’s bathhouses were raided under bawdy house laws, sex workers were similarly subjected to constant surveillance and criminalization. Radical gay liberationists, such as <a href="https://en.wikipedia.org/wiki/Gerald_Hannon">Gerald Hannon</a> and Chris Bearchell, recognized the alliance between queers and sex workers. However, during the 1980s and 1990s, as some upwardly mobile sectors of the LGBTQ community gained mainstream acceptance, the gap between these two communities widened. In Toronto, gay and straight residents supported increased policing of commercial sex in neighbourhoods such as Cabbagetown and the Village, blaming “prostitutes” and street youth for loitering, drug use, and declining property values. After the 1981 bathhouse raids, police harassment of the white, cis queer community waned, while sex workers faced new, punitive legislation criminalizing any form of public sex work. By the eve of the Pussy Palace raid in September 2000, mainstream gay and lesbian equality movements had largely distanced themselves from sex worker activism, despite both groups’ sexualities being criminalized by the state in many cases.</p>
                <p>This deep-seated mistrust of the police among sex workers is echoed in personal accounts like that of ProDomme and Pussy Palace patron Lynda J. Perry, who describes her long-standing discomfort with law enforcement. “I don’t want to be in any space where they are, you know? I’ve always felt that way towards the police,” she explains, emphasizing how even “nice cops” still maintain a desire for control, constantly looking for “anything that’s out of order, anything that’s weird.” Perry recalls how police entered her BDSM dungeon after an alarm was mistakenly triggered, even though they had already been notified that it was a false alarm. “They came anyway because they knew it was a dungeon . . . they’re, like, really nosy, and it’s none of their business.” Perry’s experiences of police interference did not end there. She recounts a more serious incident where undercover officers set her up during an escort scene. “Somebody called my escort service and wanted me to do a scene . . . and he talked me into bringing a friend. And I knew that wasn’t a good idea . . . but he sounded nice.” However, as soon as they entered the hotel room, “there was at least two cops,” and Perry and her friend were charged with living off each other’s avails, a common charge used against sex workers. Though the case was eventually thrown out, the police confiscated all of her equipment, keeping it for over a year. “That’s cops. I mean, you don’t trust them.” </p>
            
                <img style={{marginTop: '45px'}} className='banner' src='/assets/images/before/TWBC Members.jpg'></img>
                <p className='text-page-inline-caption'>A newspaper clipping in Xtra featuring members of the Toronto Women’s Bathhouse Committee (2004), photograph by RJ Martin, courtesy of The ArQuives: Canada‘s LGBTQ2+ Archives. From left: Carlyle Jansen, Carol Thames, Chanelle Gallant, JP Hornick, Janet Rowe, and Loralee Gillis.</p>
            
                <p>The organizers and activists involved with the Pussy Palace hearken back to a more radical queer history that united pro-sex activists and sex workers in a common struggle against police harassment and state surveillance, one that stands in solidarity with racialized and poor communities who have always faced disproportionate police violence. As just one example, Palace organizer Chanelle Gallant became a sex work activist following the police raid. Like the radical gay liberationists before her, Gallant emphasizes the intersections of sex work and queerness, pointing to the state’s criminalization of non-normative sexuality as the root of much harm. Reflecting on her activism, she explains how criminalization, not sex work (or queerness) itself, creates danger: </p>
                <p style={{paddingLeft: 60, paddingRight: 60}}>What I saw with sex work was that all the harms that sex workers experience were all being caused by criminalization. Even though everyone thinks they’re caused by sex work, they’re caused by the criminalization of sex work, right? Sex work is not dangerous. Criminalization makes anything dangerous. [...] Queerness was never fucking dangerous. I mean, any more than anything else is, and similar to selling sex. And so, I started to become very politicized around the damaging impacts of criminalization. </p>
                <p>Several of the Pussy Palace organizers and volunteers with experience in the sex industry ensured that Maggie’s Toronto Sex Workers Action Project, a local sex worker organization, benefited from the successful human rights complaint settled against the police. Police accountability activist and fellow Palace patron Anna Willats contextualizes the longer history of policing against Toronto’s marginalized communities in the years leading up to the September 2000 raid on the Palace (see Raid on the Palace: <a href="###">Human Rights Complaint & Class Action Suit</a>), highlighting the cyclical nature of oppression and resistance. In her view, heavy-handed policing provokes uprisings, which then justify further police brutality — a pattern that persists.</p>
                <p>In the decades before the 2000 police raid on the Pussy Palace, radical queer activists understood the alliances between sex workers and queers, all of whom faced long histories of police violence and state surveillance. The planning and organizing for the first Pussy Palace event in 1998 drew on this history of radical sex activism, while the organizers’ response to the police raid of 2000 benefited from the queer community’s longtime critique of police power and state surveillance. </p>
            
                <div className='divider' style={{marginBottom: '60px', marginTop: '60px'}}></div>
            </div>
        </div>
    )
}

export default Before;